### ISSUE TITLE
Add a flexible way of plotting frequency-based properties

### ISSUE THREAD

**Issue by kjczarne** [kjczarne/metaframe#2]
We want to e.g. see the distribution of merged/unmerged models in the context of NutritionVerse. We can use `df.hist()` but the frequencies need to be nicely collated. As a concrete example consider merged/unmerged models. Ideally the tool would traverse a directory of metadata files and would produce a histogram with two columns: how many are merged, how many are unmerged.

**Comment by isobarbaric** [comment]
can use a function I wrote to accomplish this (will do after PR review)

**Comment by isobarbaric** [comment]
running the generate_histogram method with property_name set to "merged" does the job:
generate_histogram(config, property_name="merged", data_type="discrete")
